extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dom]
pipeline = [
    "bril2json",
    "python3 ../python/test_blocks.py",
    "brili -p {args}",
]
