extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.loops]
pipeline = [
    "bril2json",
    "python3 ../python/loops.py",
    "brili -p {args}",
]

