extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "python3 ../python/lvn.py",
    "brili -p {args}",
]

[runs.tcde]
pipeline = [
    "bril2json",
    "python3 ../python/trivial_dce.py",
    "brili -p {args}",
]

[runs.lvn_tcde]
pipeline = [
    "bril2json",
    "python3 ../python/lvn.py",
    "python3 ../python/trivial_dce.py",
    "brili -p {args}",
]
